#!/usr/bin/env python3
"""Rebuild public/fonts/: the metric-compatible fonts the apps use in place of Office's.

    pip install fonttools brotli
    python3 tools/fonts.py

Downloads the fonts from github.com/google/fonts at a pinned commit, converts each file to WOFF2
unchanged (no subsetting: Carlito's license reserves its name for unmodified copies) and writes
public/fonts/LICENSES.txt from the fonts' own copyright and license records, and public/fonts/fonts.css.

| Font    | In place of | Files                                   |
|---------|-------------|-----------------------------------------|
| Carlito | Calibri     | regular, bold, italic, bold italic      |
| Caladea | Cambria     | regular, bold, italic, bold italic      |
| Gelasio | Georgia     | variable weight 400-700, upright/italic |

Arial, Times New Roman and Courier New are left to the computer: Windows, macOS, iOS and ChromeOS
have them (ChromeOS as Arimo, Tinos, Cousine) and Linux desktops usually have the Liberation fonts
of the same widths; the font stacks in common/core.js name those.
"""
import io
import os
import urllib.request

from fontTools.ttLib import TTFont

COMMIT = '51303ca9e8ac9dcea7b12d307ba568fd0e6fcfca'   # google/fonts main, 2026-10-09
RAW = 'https://raw.githubusercontent.com/google/fonts/' + COMMIT + '/ofl/'
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public', 'fonts')
VARIABLE = ['Gelasio']
STATIC = ['Carlito', 'Caladea']
STYLES = ['Regular', 'Bold', 'Italic', 'BoldItalic']


def fetch(path):
    with urllib.request.urlopen(RAW + path.replace('[', '%5B').replace(']', '%5D')) as r:
        return r.read()


def files():
    for family in VARIABLE:
        yield family, family + '[wght].ttf', family + '.woff2'
        yield family, family + '-Italic[wght].ttf', family + '-Italic.woff2'
    for family in STATIC:
        for style in STYLES:
            yield family, family + '-' + style + '.ttf', family + '-' + style + '.woff2'


def stylesheet():
    """@font-face rules: an installed copy of the stand-in (local) first, else the WOFF2 file.
    Each weight gets its own rule, so a fixed-weight installed copy never stands in for bold."""
    faces = []
    for family in VARIABLE + STATIC:
        for style, weight, italic in [('Regular', 400, False), ('Bold', 700, False), ('Italic', 400, True), ('BoldItalic', 700, True)]:
            names = [family + ' ' + {'Regular': 'Regular', 'Bold': 'Bold', 'Italic': 'Italic', 'BoldItalic': 'Bold Italic'}[style], family + '-' + style]
            if style == 'Regular':
                names.insert(0, family)
            file = family + ('-Italic' if italic else '') + '.woff2' if family in VARIABLE else family + '-' + style + '.woff2'
            src = ', '.join("local('%s')" % n for n in names) + ", url('%s') format('woff2')" % file
            faces.append("@font-face { font-family: '%s'; font-style: %s; font-weight: %d; font-display: swap;\n  src: %s; }"
                         % (family, 'italic' if italic else 'normal', weight, src))
    return ('/* Metric-compatible stand-ins for Office\'s fonts (licences: LICENSES.txt). Generated by tools/fonts.py.\n'
            ' * Pages name the real font first ("Calibri","Carlito",...: L.fontStack), so a browser downloads one of\n'
            ' * these files only when the machine lacks the real font and text in that style is on screen.\n'
            ' * Gelasio is a variable font: its bold rules use the same file at weight 700.\n */\n'
            + '\n'.join(faces) + '\n')


def main():
    os.makedirs(OUT, exist_ok=True)
    notices = {}
    for family, source, target in files():
        # keep the font's own dates and bounds: a conversion only, and the same bytes on every rebuild
        font = TTFont(io.BytesIO(fetch(family.lower() + '/' + source)), recalcTimestamp=False, recalcBBoxes=False)
        notices.setdefault(family, font['name'].getDebugName(0))
        font.flavor = 'woff2'
        font.save(os.path.join(OUT, target))
        print(target, os.path.getsize(os.path.join(OUT, target)))
    # The OFL text is the same for every family (taken from Gelasio's copy); each family keeps its own notice.
    ofl = fetch('gelasio/OFL.txt').decode('utf-8')
    licence = ofl[ofl.index('This Font Software is licensed'):]
    with open(os.path.join(OUT, 'LICENSES.txt'), 'w', encoding='utf-8') as out:
        out.write('Fonts in this folder: WOFF2 conversions, otherwise unmodified, of the files in\n')
        out.write('https://github.com/google/fonts/tree/' + COMMIT + '/ofl\n')
        out.write('(carlito, caladea, gelasio). Rebuilt by tools/fonts.py.\n\n')
        for family in VARIABLE + STATIC:
            note = notices[family]
            if family == 'Carlito' and 'Reserved Font Name' not in note:
                note += ', with Reserved Font Name "Carlito"'   # as in Carlito's OFL.txt
            out.write(family + ': ' + note + '\n')
        out.write('\n' + licence)
    with open(os.path.join(OUT, 'fonts.css'), 'w', encoding='utf-8') as out:
        out.write(stylesheet())


if __name__ == '__main__':
    main()
